/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.JOptionPane;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;

/**
 *
 * @author akari
 */
public class NurseAppointmentsGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NurseAppointmentsGUI.class.getName());
    private static final String FILE_PATH = "data/appointments.txt";
    private java.awt.Frame parentFrame;
    private String loggedInNurseId;

    public NurseAppointmentsGUI() {
        this(null, "guest");
    }

    /**
     * Creates new form Appointments
     */
    public NurseAppointmentsGUI(java.awt.Frame parent, String nurseId) {
        initComponents();
        this.parentFrame = parent;
        this.loggedInNurseId = nurseId;
        loadAppointments();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Appointment");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"A001", "P010", "doc1", "nurse1", "Completed", "<html>General<br>checkup</html>", "2026-06-24", "12:30"},
                {"A002", "P014", "doc1", "nurse1", "Ongoing", "Follow-up", "2026-06-24", "3:30"},
                {"A003", "P019", "doc2", "nurse1", "Scheduled-06-25", "Checkup", "2026-06-29", "9:30"},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "<html>Appointment<br>ID</html>", "Patient ID", "Doctor ID", "NurseID", "Status", "Type", "Date", "Time"
            }
        ));
        jTable1.setRowHeight(50);
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update Status");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 238, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(459, 459, 459))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loadAppointments();   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        updateStatus();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        goBack();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void loadAppointments() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        File file = new File(FILE_PATH);
        if (!file.exists()) {
            JOptionPane.showMessageDialog(this,
                    "appointments.txt not found at " + file.getAbsolutePath(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.trim().isEmpty()) {
                    continue;
                }
                String[] parts = line.split(",", -1);
                if (parts.length != 8) {
                    continue; // skip malformed lines instead of crashing
                }
                if (!loggedInNurseId.equals("guest")
                        && !parts[3].equalsIgnoreCase(loggedInNurseId)) {
                    continue;
                }
                model.addRow(new Object[]{parts[0], parts[1], parts[2], parts[3],
                    parts[7], parts[6], parts[4], parts[5]});
            }
        } catch (IOException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,
                    "Error reading appointments file.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void updateStatus() {
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this,
                    "Please select an appointment first.",
                    "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String appointmentId = jTable1.getValueAt(row, 0).toString();
        String[] statusOptions = {"Ongoing", "Completed", "Cancelled"};

        String newStatus = (String) JOptionPane.showInputDialog(
                this,
                "Select new status for " + appointmentId + ":",
                "Update Status",
                JOptionPane.QUESTION_MESSAGE,
                null,
                statusOptions,
                statusOptions[0]
        );

        if (newStatus == null) {
            return; // user cancelled
        }

        if (saveStatusToFile(appointmentId, newStatus)) {
            jTable1.setValueAt(newStatus, row, 4);
            JOptionPane.showMessageDialog(this, "Status updated successfully.");
        } else {
            JOptionPane.showMessageDialog(this,
                    "Could not update status. Appointment not found in file.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private boolean saveStatusToFile(String appointmentId, String newStatus) {
        File file = new File(FILE_PATH);
        ArrayList<String> lines = new ArrayList<>();
        boolean found = false;

        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.trim().isEmpty()) {
                    lines.add(line);
                    continue;
                }
                String[] parts = line.split(",", -1);
                if (parts.length >= 8 && parts[0].equals(appointmentId)) {
                    parts[7] = newStatus;
                    lines.add(String.join(",", parts));
                    found = true;
                } else {
                    lines.add(line);
                }
            }
        } catch (IOException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
            return false;
        }

        if (!found) {
            return false;
        }

        try (PrintWriter writer = new PrintWriter(new FileWriter(file))) {
            for (String l : lines) {
                writer.println(l);
            }
        } catch (IOException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
            return false;
        }

        return true;
    }

    /**
     * Closes this window and shows the dashboard that opened it (if any).
     */
    private void goBack() {
        this.dispose();
        if (parentFrame != null) {
            parentFrame.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form (standalone test, no parent dashboard) */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NurseAppointmentsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
